//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseSpot.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HorseSpot.Infrastructure.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action requires additional rights..
        /// </summary>
        public static string ActionRequiresAdditionalRights {
            get {
                return ResourceManager.GetString("ActionRequiresAdditionalRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already in our subscribers list..
        /// </summary>
        public static string AlreadyRegistredSubscriber {
            get {
                return ResourceManager.GetString("AlreadyRegistredSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment date cannot be in the past..
        /// </summary>
        public static string AppointmentCannotBeInPast {
            get {
                return ResourceManager.GetString("AppointmentCannotBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have more than five pictures per advertisment..
        /// </summary>
        public static string CannotHaveMoreThan5PerAd {
            get {
                return ResourceManager.GetString("CannotHaveMoreThan5PerAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save external login..
        /// </summary>
        public static string CannotSaveExternalLogin {
            get {
                return ResourceManager.GetString("CannotSaveExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot upload more than five pictures..
        /// </summary>
        public static string CannotUploadMoreThan5 {
            get {
                return ResourceManager.GetString("CannotUploadMoreThan5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given URL is not allowed by Client_id &apos;{0}&apos; configuration..
        /// </summary>
        public static string ClientIdDoesNotHaveEnoughRight {
            get {
                return ResourceManager.GetString("ClientIdDoesNotHaveEnoughRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client_Id is required..
        /// </summary>
        public static string ClientIdIsRequired {
            get {
                return ResourceManager.GetString("ClientIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client_id &apos;{0}&apos; is not registered in the system..
        /// </summary>
        public static string ClientIdNotRegistred {
            get {
                return ResourceManager.GetString("ClientIdNotRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client is inactive..
        /// </summary>
        public static string ClientInactive {
            get {
                return ResourceManager.GetString("ClientInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret should be sent..
        /// </summary>
        public static string ClientSecretShouldBeSent {
            get {
                return ResourceManager.GetString("ClientSecretShouldBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password field didn&apos;t match Password field..
        /// </summary>
        public static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not registred..
        /// </summary>
        public static string EmailDoesNotExist {
            get {
                return ResourceManager.GetString("EmailDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this email is already registered..
        /// </summary>
        public static string ExistUserEmail {
            get {
                return ResourceManager.GetString("ExistUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this username is already registered..
        /// </summary>
        public static string ExistUserUsername {
            get {
                return ResourceManager.GetString("ExistUserUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exteranl user is not registred..
        /// </summary>
        public static string ExternalUserIsNotRegistred {
            get {
                return ResourceManager.GetString("ExternalUserIsNotRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image was not found in the advertisment images list..
        /// </summary>
        public static string ImageNotFoundInAdImagesList {
            get {
                return ResourceManager.GetString("ImageNotFoundInAdImagesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inccorect current password..
        /// </summary>
        public static string InccorectCurrentPassword {
            get {
                return ResourceManager.GetString("InccorectCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid horse ability identifier..
        /// </summary>
        public static string InvalidAbilityIdentifier {
            get {
                return ResourceManager.GetString("InvalidAbilityIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid advertisment identifier..
        /// </summary>
        public static string InvalidAdIdentifier {
            get {
                return ResourceManager.GetString("InvalidAdIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid change password request..
        /// </summary>
        public static string InvalidChangePasswordRequest {
            get {
                return ResourceManager.GetString("InvalidChangePasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret is invalid..
        /// </summary>
        public static string InvalidClientSecret {
            get {
                return ResourceManager.GetString("InvalidClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password field didn&apos;t match Password field.
        /// </summary>
        public static string InvalidConfirmPasswordFormat {
            get {
                return ResourceManager.GetString("InvalidConfirmPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid edit profile request..
        /// </summary>
        public static string InvalidEditProfileRequest {
            get {
                return ResourceManager.GetString("InvalidEditProfileRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid external login request..
        /// </summary>
        public static string InvalidExternalLoginRequest {
            get {
                return ResourceManager.GetString("InvalidExternalLoginRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid horse advertisment request..
        /// </summary>
        public static string InvalidHorseAdRequest {
            get {
                return ResourceManager.GetString("InvalidHorseAdRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid horse gender identifier..
        /// </summary>
        public static string InvalidHorseGenderIdentifier {
            get {
                return ResourceManager.GetString("InvalidHorseGenderIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login request..
        /// </summary>
        public static string InvalidLoginRequest {
            get {
                return ResourceManager.GetString("InvalidLoginRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid make appointment request..
        /// </summary>
        public static string InvalidMakeAppRequest {
            get {
                return ResourceManager.GetString("InvalidMakeAppRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message field cannot be empty..
        /// </summary>
        public static string InvalidMessageFormat {
            get {
                return ResourceManager.GetString("InvalidMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should have at least six characters..
        /// </summary>
        public static string InvalidPasswordFormat {
            get {
                return ResourceManager.GetString("InvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number should be like 0123456789 or +40757520997.
        /// </summary>
        public static string InvalidPhoneNumberFormat {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid picture format..
        /// </summary>
        public static string InvalidPictureFormat {
            get {
                return ResourceManager.GetString("InvalidPictureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid picture identifier..
        /// </summary>
        public static string InvalidPictureIdentifier {
            get {
                return ResourceManager.GetString("InvalidPictureIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price range identifier..
        /// </summary>
        public static string InvalidPriceRangeIdentifier {
            get {
                return ResourceManager.GetString("InvalidPriceRangeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Provider or External Token..
        /// </summary>
        public static string InvalidProviderOrExternalToken {
            get {
                return ResourceManager.GetString("InvalidProviderOrExternalToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recommended rider identifier..
        /// </summary>
        public static string InvalidRecommendedRiderIdentifier {
            get {
                return ResourceManager.GetString("InvalidRecommendedRiderIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirect_uri is invalid..
        /// </summary>
        public static string InvalidRedirectUri {
            get {
                return ResourceManager.GetString("InvalidRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration request..
        /// </summary>
        public static string InvalidRegistrationRequest {
            get {
                return ResourceManager.GetString("InvalidRegistrationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid send email request..
        /// </summary>
        public static string InvalidSendEmailRequest {
            get {
                return ResourceManager.GetString("InvalidSendEmailRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user identifier..
        /// </summary>
        public static string InvalidUserIdentifier {
            get {
                return ResourceManager.GetString("InvalidUserIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one ability..
        /// </summary>
        public static string MustSelectAtLeastOneAbility {
            get {
                return ResourceManager.GetString("MustSelectAtLeastOneAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one recommended rider..
        /// </summary>
        public static string MustSelectAtLeastOneRecommendedRider {
            get {
                return ResourceManager.GetString("MustSelectAtLeastOneRecommendedRider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update at least one image..
        /// </summary>
        public static string PleaseUpdateAtLeastOneImage {
            get {
                return ResourceManager.GetString("PleaseUpdateAtLeastOneImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is issued to a different clientId..
        /// </summary>
        public static string RefreshTokenIssuedToDifferentClient {
            get {
                return ResourceManager.GetString("RefreshTokenIssuedToDifferentClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection forbidden..
        /// </summary>
        public static string WebSocketConnectionForbidden {
            get {
                return ResourceManager.GetString("WebSocketConnectionForbidden", resourceCulture);
            }
        }
    }
}
