export let AppointmentStatus = {
    CREATED: "CREATED",
    DATE_CHANGED_BY_OWNER: "DATE_CHANGED_BY_OWNER",
    DATE_CHANGED_BY_INITIATOR: "DATE_CHANGED_BY_INITIATOR",
    ACCEPTED_BY_OWNER: "ACCEPTED_BY_OWNER",
    ACCEPTED_BY_INITIATOR: "ACCEPTED_BY_INITIATOR",
    SET_SEEN_APPOINTMETS: "SET_SEEN_APPOINTMETS",
}
 
export * from './appointment.status';